{"name": "test_divide_by_zero", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "def test_divide_by_zero():\n        # with pytest.raises(ZeroDivisionError):\n>       divide(4, 0)\n\ntest_my_function.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nnum1 = 4, num2 = 0\n\n    def divide(num1, num2):\n>       return num1 / num2\nE       ZeroDivisionError: division by zero\n\nmy_function.py:14: ZeroDivisionError"}, "start": 1715785663876, "stop": 1715785663876, "uuid": "ae127d49-a0a4-4e2e-b172-039b3346e8d0", "historyId": "27ec9e66bec64b03a2f812b76b4ffc22", "testCaseId": "27ec9e66bec64b03a2f812b76b4ffc22", "fullName": "test.test_my_function#test_divide_by_zero", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_my_function"}, {"name": "host", "value": "H"}, {"name": "thread", "value": "3956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_my_function"}]}