{"name": "test_divide_by_zero", "status": "broken", "statusDetails": {"message": "ZeroDivisionError", "trace": "def test_divide_by_zero():\n        with pytest.raises(ValueError):\n>           divide(1, 0)\n\ntest_my_function.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nnum1 = 1, num2 = 0\n\n    def divide(num1, num2):\n        if num2 == 0:\n>           raise ZeroDivisionError #設置一個value錯誤，但是在test裡面是設置ZeroDivisionError，所以會報錯\nE           ZeroDivisionError\n\nmy_function.py:8: ZeroDivisionError"}, "start": 1715786028167, "stop": 1715786028168, "uuid": "529d22e6-8126-4ca4-8af7-6abe897bff25", "historyId": "27ec9e66bec64b03a2f812b76b4ffc22", "testCaseId": "27ec9e66bec64b03a2f812b76b4ffc22", "fullName": "test.test_my_function#test_divide_by_zero", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_my_function"}, {"name": "host", "value": "H"}, {"name": "thread", "value": "13392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_my_function"}]}