{"name": "test_divide_by_zero", "status": "broken", "statusDetails": {"message": "ValueError", "trace": "def test_divide_by_zero():\n        with pytest.raises(ZeroDivisionError):\n>           divide(1, 0)\n\ntest_my_function.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nnum1 = 1, num2 = 0\n\n    def divide(num1, num2):\n        if num2 == 0:\n>           raise  ValueError #設置一個value錯誤，但是在test裡面是設置ZeroDivisionError，所以會報錯\nE           ValueError\n\nmy_function.py:8: ValueError"}, "start": 1715786082657, "stop": 1715786082657, "uuid": "8e9def49-8c08-49e6-bb60-d904c3d5250b", "historyId": "27ec9e66bec64b03a2f812b76b4ffc22", "testCaseId": "27ec9e66bec64b03a2f812b76b4ffc22", "fullName": "test.test_my_function#test_divide_by_zero", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_my_function"}, {"name": "host", "value": "H"}, {"name": "thread", "value": "14836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_my_function"}]}